### ISSUE TITLE
python3 xx.py(from Readme.md) failed,while same code execute in python3 reading data sucess.

### ISSUE THREAD

**Issue by ouahirog** [h4/lywsd02#9]
pi@raspberrypi:/tmp $ cat bb.py
from lywsd02 import Lywsd02Client
mac = 'F7:2E:00:B2:38:35'
client = Lywsd02Client(mac)
print(client.temperature)
pi@raspberrypi:/tmp $ python3 bb.py
Traceback (most recent call last):
  File "bb.py", line 4, in <module>
    print(cclient.temperature)
  File "/home/pi/.local/lib/python3.7/site-packages/lywsd02/client.py", line 44, in temperature
    self._get_sensor_data()
  File "/home/pi/.local/lib/python3.7/site-packages/lywsd02/decorators.py", line 3, in wrapper
    self._peripheral.connect(self._mac)
  File "/home/pi/.local/lib/python3.7/site-packages/bluepy/btle.py", line 445, in connect
    self._connect(addr, addrType, iface)
  File "/home/pi/.local/lib/python3.7/site-packages/bluepy/btle.py", line 439, in _connect
    raise BTLEDisconnectError("Failed to connect to peripheral %s, addr type: %s" % (addr, addrType), rsp)
bluepy.btle.BTLEDisconnectError: Failed to connect to peripheral F7:2E:00:B2:38:35, addr type: public
pi@raspberrypi:/tmp $ python3
Python 3.7.3 (default, Apr  3 2019, 05:39:12)
[GCC 8.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from lywsd02 import Lywsd02Client
>>> mac = 'E7:2E:00:B2:38:35'
>>> client = Lywsd02Client(mac)
>>> print(client.temperature)
20.36
>>>

**Comment by h4** [comment]
In most cases this issue related to distance between sensor and HA server.
